// Writes migrations/0001_seed.sql: every base entry and the "Basis" list, owned by `system`.
// Run with `bun run db:seed` after changing static/data.json, then apply migrations.
import { readFileSync, writeFileSync } from "node:fs";
import { entriesFromDeck } from "../src/lib/domain/entries";
import type { Deck } from "../src/lib/domain/types";
import { entryToRow } from "../src/lib/server/db/mapping";
import { BASE_LIST_ID, BASE_LIST_NAME, SYSTEM_OWNER_ID } from "../src/lib/server/db/schema";

// Fixed so regenerating the seed from unchanged data produces an identical file.
const SEED_TIMESTAMP = Date.UTC(2026, 0, 1);
const OUTPUT = "migrations/0001_seed.sql";

function sql(value: string | number | null): string {
  if (value === null) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${value.replaceAll("'", "''")}'`;
}

const deck = JSON.parse(readFileSync("static/data.json", "utf8")) as Deck;
const entries = entriesFromDeck(deck);
const lines = [
  "-- Generated by scripts/seed.ts from static/data.json. Do not edit by hand.",
];

for (const entry of entries) {
  const row = entryToRow(entry, {
    ownerId: SYSTEM_OWNER_ID,
    visibility: "public",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  });
  const values = [
    row.id,
    row.type,
    row.ownerId,
    row.visibility,
    row.data,
    row.searchText,
    row.createdAt,
    row.updatedAt,
  ];
  lines.push(
    `INSERT OR REPLACE INTO entries (id, type, owner_id, visibility, data, search_text, created_at, updated_at) VALUES (${values.map(sql).join(", ")});`,
  );
}

lines.push(
  `INSERT OR REPLACE INTO lists (id, owner_id, name, visibility, share_slug, created_at, updated_at) VALUES (${[
    BASE_LIST_ID,
    SYSTEM_OWNER_ID,
    BASE_LIST_NAME,
    "public",
    null,
    SEED_TIMESTAMP,
    SEED_TIMESTAMP,
  ]
    .map(sql)
    .join(", ")});`,
);

entries.forEach((entry, position) => {
  lines.push(
    `INSERT OR REPLACE INTO list_entries (list_id, entry_id, position, added_at) VALUES (${[
      BASE_LIST_ID,
      entry.id,
      position,
      SEED_TIMESTAMP,
    ]
      .map(sql)
      .join(", ")});`,
  );
});

writeFileSync(OUTPUT, `${lines.join("\n--> statement-breakpoint\n")}\n`);
console.log(`Wrote ${entries.length} entries and the base list to ${OUTPUT}`);
